<?php
    //parametros de conexion (opcionales)
    //$servidor  = "192.168.43.146";
	$servidor  = "10.90.31.207";
    $basedatos = "mybox";
    $usuario   = "root";
    $contra    = "utn";
	
    //suprime advertencias
    error_reporting(0);

	//proceso para conectar con el servidor 
    if(!$conex = mysqli_connect($servidor, $usuario, $contra, $basedatos)){
        echo "<h3><font color='red'>Error: No se puede conectar al servidor de MySQL.</font></h3>" . "<hr>";
        echo "<strong>Número........:</strong> " . mysqli_connect_errno() . "<br>";
        echo "<strong>Descripción...:</strong> " . mysqli_connect_error() . "<br>";
        exit;          
    }   
?>